python backbone
KIT-CMS/ToBeNamedPrototype pull request #17
Opened 2021-04-30 13:55 UTC by swozniewski

Develops python backbone such that current example analysis.cxx can be reproduced.
In addition, an exemplary shift is introduced. Note, that filtering with shift needs better treatment.
Channel specific treatment not yet implemented.
Some cpp modules are modified to better fit a common structure.

2021-04-30 18:57 UTC, stwunsch commented on quantities.hxx
>          [](const ROOT::Math::PtEtaPhiMVector &p4) { return p4.pt(); },
Hier muesst ihr aufpassen, das schreibt euch ein double raus und ihr habt am Ende evtl ein 2x so grosses ntuple ;) Selbes gilt auch fuer die anderen quantities unten.

```suggestion
        [](const ROOT::Math::PtEtaPhiMVector &p4) { return (return) p4.pt(); },
```

2021-05-03 15:07 UTC, harrypuuter requested changes

2021-05-03 15:07 UTC, harrypuuter commented on code_generation/producer.py
> +            for qy in self.inputs:
`qy` should be `quantity` ?

2021-05-03 15:07 UTC, harrypuuter commented on code_generation/producer.py
> +            l = len(config[shift][self.vec_configs[0]])
switch from `l` to some longer more descriptive variable name

2021-05-03 15:07 UTC, harrypuuter commented on code_generation/producer.py
> +            for p in self.producers:
`for producer in self.producers`

2021-05-03 15:23 UTC, harrypuuter approved these changes

2021-05-03 15:24 UTC, merged